/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aed.linkedlist;

import org.junit.Before;
import org.junit.Ignore;
import org.junit.Test;
import static org.junit.Assert.*;


import aed.linkedlist.LinkedList;

public class LinkedListTest {

  LinkedList linkedlist;

  @Before
  public void initialize(){
    linkedlist = new LinkedList<String>();
    linkedlist.add("Daniel");
    linkedlist.add("Rocha");
    linkedlist.add("Silva");
  }
    
  @Test 
  public void shouldAddElementsOntheListLinked() {

    final int expectElementsInTheLinkedList = 3;
    assertEquals(linkedlist.length(), expectElementsInTheLinkedList);

  }

  @Test
  public void shouldReturnTheNIndexElementInTheLinkedList() {
  
    final String expectElement = "Rocha";
    final int index = 1;

    assertEquals(linkedlist.get(index), expectElement);
  }
  
  @Test
  public void shouldCloneLinkedList() {

    var cloneLinkedList = linkedlist.clone();

    assertEquals(cloneLinkedList.length(), linkedlist.length());
    for(int i = 0; i < linkedlist.length(); i++) {
      assertEquals(linkedlist.get(i), cloneLinkedList.get(i));
    } 
  }
  
  @Test
  public void shouldClearLinkedList() {
    var cloneLinkedList = linkedlist.clone();
    cloneLinkedList.clear();

    final boolean empty = true;
    final int length = 0;

    assertEquals(cloneLinkedList.isEmpty(), empty);
    assertEquals(cloneLinkedList.length(), length);
  }

  @Test
  public void shouldReturnIfcontainsElementWithTrue() {
    final String element = "Rocha";
    final boolean expect = true;
    assertEquals(linkedlist.contains(element), expect);
  }
  
  @Test
  public void shouldReturnIfcontainsElementWithFalse() {
    final String element = "Rocha Silva";
    final boolean expect = false;
    assertEquals(linkedlist.contains(element), expect);
    
  }


  @Test
  public void shouldReturnIfCustomContainsElementWithFalse() {
    final String element = "Rocha";
    final boolean expect = true;
    assertEquals(linkedlist.contains(element, (a, b) -> a.equals(b)), expect);

  }

  @Test
  public void shouldAddInTheCustomIndexInTheLinkedList() {
    var cloneLinkedList = linkedlist.clone();
    var element = "Pereira";
    var index = 2;
    cloneLinkedList.add(index, element);
    
    assertEquals(cloneLinkedList.get(index), element);
  }

  @Test
  public void shouldReturnIndexOfElementInTheLinkedList() {
    var element = "Rocha";

    final int index = 1;
    assertEquals(linkedlist.indexOf(element), index);
  }

  @Test
  public void shouldReturnMinusOneIfThereIsNoElementInTheLinkedList() {
    var element = "Pereira";
    final int index = -1;
    assertEquals(linkedlist.indexOf(element), index);
  }

  @Test
  public void shouldRemoveTheElementLinkedList() {
    var cloneLinkedList = linkedlist.clone();
    var expectLength = cloneLinkedList.length() - 1;
    cloneLinkedList.remove(0);

    assertEquals(cloneLinkedList.length(), expectLength);
  }

  @Test
  public void shouldUpdateElementValueInTheLinkedList() {
    
    var cloneLinkedList = linkedlist.clone();
    var value = "Pereira";
    var index = 1;

    cloneLinkedList.set(index, value);
    assertEquals(cloneLinkedList.get(index), value);
  }

  @Test
  public void throwIndexOutOfBoundsExceptionWhenAddingElementInTheInvalidIndex() {
    assertThrows(IndexOutOfBoundsException.class, () -> {
      var element = "Pereira";
      var invalidIndex = Integer.MAX_VALUE;
      linkedlist.add(invalidIndex, element);
    });
  }

  @Test
  public void throwIndexOutOfBoundsExceptionWhenRemovingElementInTheInvalidIndex() {
    assertThrows(IndexOutOfBoundsException.class, () -> {
      var invalidIndex = Integer.MAX_VALUE;
      linkedlist.remove(invalidIndex);
    });
  }

  @Test
  public void throwIndexOutOfBoundsExceptionWhenSettingElementInTheInvalidIndex() {
    assertThrows(IndexOutOfBoundsException.class, () -> {
      var element = "Pereira";
      var invalidIndex = Integer.MAX_VALUE;
      linkedlist.set(invalidIndex, element);
    });
  }
}
