/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package aed.queue;


import org.junit.Before;
import org.junit.Test;
import static org.junit.Assert.assertEquals;


public class QueueTest {
  Queue<String> queue;

  @Before
  public void initialize() {
    queue = new Queue<String>();
    queue.add("Daniel");
    queue.add("Rocha");
    queue.add("Silva");
  }

  @Test
  public void veriryIfFirstQueueIsCorrect() {
    var element = queue.peek();
    var expect = "Daniel";
    assertEquals(element, expect);
  }

  @Test
  public void verifyIfElementIsRemovedWhenIsGetTheFirstOfTheQueue() {

    var expectLength = queue.length() - 1;
    var expectElement = "Daniel";

    var element = queue.pool();

    assertEquals(element, expectElement);
    assertEquals(queue.length(), expectLength);
  }

  @Test
  public void shouldCloneQueue() {
    var queueClone = queue.clone();
    
    assertEquals(queueClone.length(), queue.length());

    while(!queueClone.isEmpty()) {
      var elementA = queueClone.pool();
      var elementB = queue.pool();
      assertEquals(elementA, elementB);
      queue.add(elementB);
    }
  }
}
